-- S&P 500 Ticker Universe Seed Data
-- This file seeds the ticker_universe table with S&P 500 companies

INSERT OR IGNORE INTO ticker_universe (id, ticker, name, sector, industry, market_cap_billion, is_sp500, is_active, created_at, updated_at) VALUES
-- Technology
('sp500-aapl', 'AAPL', 'Apple Inc.', 'Technology', 'Consumer Electronics', 2800.0, 1, 1, datetime('now'), datetime('now')),
('sp500-msft', 'MSFT', 'Microsoft Corporation', 'Technology', 'Software', 2700.0, 1, 1, datetime('now'), datetime('now')),
('sp500-nvda', 'NVDA', 'NVIDIA Corporation', 'Technology', 'Semiconductors', 2200.0, 1, 1, datetime('now'), datetime('now')),
('sp500-googl', 'GOOGL', 'Alphabet Inc.', 'Technology', 'Internet Services', 1700.0, 1, 1, datetime('now'), datetime('now')),
('sp500-goog', 'GOOG', 'Alphabet Inc. Class C', 'Technology', 'Internet Services', 1700.0, 1, 1, datetime('now'), datetime('now')),
('sp500-meta', 'META', 'Meta Platforms Inc.', 'Technology', 'Internet Services', 900.0, 1, 1, datetime('now'), datetime('now')),
('sp500-amzn', 'AMZN', 'Amazon.com Inc.', 'Consumer Cyclical', 'E-Commerce', 1500.0, 1, 1, datetime('now'), datetime('now')),
('sp500-tsla', 'TSLA', 'Tesla Inc.', 'Consumer Cyclical', 'Auto Manufacturers', 700.0, 1, 1, datetime('now'), datetime('now')),
('sp500-avgo', 'AVGO', 'Broadcom Inc.', 'Technology', 'Semiconductors', 700.0, 1, 1, datetime('now'), datetime('now')),
('sp500-orcl', 'ORCL', 'Oracle Corporation', 'Technology', 'Software', 350.0, 1, 1, datetime('now'), datetime('now')),
('sp500-adbe', 'ADBE', 'Adobe Inc.', 'Technology', 'Software', 200.0, 1, 1, datetime('now'), datetime('now')),
('sp500-crm', 'CRM', 'Salesforce Inc.', 'Technology', 'Software', 250.0, 1, 1, datetime('now'), datetime('now')),
('sp500-intc', 'INTC', 'Intel Corporation', 'Technology', 'Semiconductors', 180.0, 1, 1, datetime('now'), datetime('now')),
('sp500-amd', 'AMD', 'Advanced Micro Devices', 'Technology', 'Semiconductors', 250.0, 1, 1, datetime('now'), datetime('now')),
('sp500-ibm', 'IBM', 'International Business Machines', 'Technology', 'Information Technology Services', 160.0, 1, 1, datetime('now'), datetime('now')),
('sp500-qcom', 'QCOM', 'Qualcomm Inc.', 'Technology', 'Semiconductors', 180.0, 1, 1, datetime('now'), datetime('now')),
('sp500-txn', 'TXN', 'Texas Instruments', 'Technology', 'Semiconductors', 170.0, 1, 1, datetime('now'), datetime('now')),
('sp500-now', 'NOW', 'ServiceNow Inc.', 'Technology', 'Software', 180.0, 1, 1, datetime('now'), datetime('now')),
('sp500-intu', 'INTU', 'Intuit Inc.', 'Technology', 'Software', 170.0, 1, 1, datetime('now'), datetime('now')),
('sp500-amat', 'AMAT', 'Applied Materials Inc.', 'Technology', 'Semiconductor Equipment', 130.0, 1, 1, datetime('now'), datetime('now')),
('sp500-mu', 'MU', 'Micron Technology', 'Technology', 'Semiconductors', 120.0, 1, 1, datetime('now'), datetime('now')),
('sp500-lrcx', 'LRCX', 'Lam Research Corp', 'Technology', 'Semiconductor Equipment', 110.0, 1, 1, datetime('now'), datetime('now')),
('sp500-klac', 'KLAC', 'KLA Corporation', 'Technology', 'Semiconductor Equipment', 90.0, 1, 1, datetime('now'), datetime('now')),
('sp500-adsk', 'ADSK', 'Autodesk Inc.', 'Technology', 'Software', 60.0, 1, 1, datetime('now'), datetime('now')),
('sp500-fisv', 'FISV', 'Fiserv Inc.', 'Technology', 'Software', 70.0, 1, 1, datetime('now'), datetime('now')),
('sp500-gww', 'GWW', 'W.W. Grainger Inc.', 'Industrials', 'Industrial Distribution', 45.0, 1, 1, datetime('now'), datetime('now')),
('sp500-fico', 'FICO', 'Fair Isaac Corp', 'Technology', 'Software', 35.0, 1, 1, datetime('now'), datetime('now')),
('sp500-snps', 'SNPS', 'Synopsys Inc.', 'Technology', 'Software', 80.0, 1, 1, datetime('now'), datetime('now')),
('sp500-cdns', 'CDNS', 'Cadence Design Systems', 'Technology', 'Software', 75.0, 1, 1, datetime('now'), datetime('now')),
('sp500-ftnt', 'FTNT', 'Fortinet Inc.', 'Technology', 'Software', 55.0, 1, 1, datetime('now'), datetime('now')),
('sp500-panw', 'PANW', 'Palo Alto Networks', 'Technology', 'Software', 90.0, 1, 1, datetime('now'), datetime('now')),
('sp500-net', 'NET', 'Cloudflare Inc.', 'Technology', 'Software', 35.0, 1, 1, datetime('now'), datetime('now')),
('sp500-zs', 'ZS', 'Zscaler Inc.', 'Technology', 'Software', 25.0, 1, 1, datetime('now'), datetime('now')),
('sp500-crwd', 'CRWD', 'CrowdStrike Holdings', 'Technology', 'Software', 70.0, 1, 1, datetime('now'), datetime('now')),
('sp500-datadog', 'DDOG', 'Datadog Inc.', 'Technology', 'Software', 35.0, 1, 1, datetime('now'), datetime('now')),
('sp500-snow', 'SNOW', 'Snowflake Inc.', 'Technology', 'Software', 50.0, 1, 1, datetime('now'), datetime('now')),
('sp500-pltr', 'PLTR', 'Palantir Technologies', 'Technology', 'Software', 100.0, 1, 1, datetime('now'), datetime('now')),

-- Financials
('sp500-brk-b', 'BRK.B', 'Berkshire Hathaway', 'Financials', 'Insurance', 850.0, 1, 1, datetime('now'), datetime('now')),
('sp500-jpm', 'JPM', 'JPMorgan Chase & Co.', 'Financials', 'Banks', 550.0, 1, 1, datetime('now'), datetime('now')),
('sp500-v', 'V', 'Visa Inc.', 'Financials', 'Payment Processing', 550.0, 1, 1, datetime('now'), datetime('now')),
('sp500-ma', 'MA', 'Mastercard Inc.', 'Financials', 'Payment Processing', 450.0, 1, 1, datetime('now'), datetime('now')),
('sp500-bac', 'BAC', 'Bank of America Corp', 'Financials', 'Banks', 300.0, 1, 1, datetime('now'), datetime('now')),
('sp500-wfc', 'WFC', 'Wells Fargo & Co.', 'Financials', 'Banks', 200.0, 1, 1, datetime('now'), datetime('now')),
('sp500-gs', 'GS', 'Goldman Sachs Group', 'Financials', 'Investment Banking', 150.0, 1, 1, datetime('now'), datetime('now')),
('sp500-ms', 'MS', 'Morgan Stanley', 'Financials', 'Investment Banking', 150.0, 1, 1, datetime('now'), datetime('now')),
('sp500-blk', 'BLK', 'BlackRock Inc.', 'Financials', 'Asset Management', 130.0, 1, 1, datetime('now'), datetime('now')),
('sp500-schg', 'SCHW', 'Charles Schwab Corp', 'Financials', 'Brokerage', 130.0, 1, 1, datetime('now'), datetime('now')),
('sp500-axp', 'AXP', 'American Express Co.', 'Financials', 'Credit Services', 140.0, 1, 1, datetime('now'), datetime('now')),
('sp500-c', 'C', 'Citigroup Inc.', 'Financials', 'Banks', 100.0, 1, 1, datetime('now'), datetime('now')),
('sp500-pgr', 'PGR', 'Progressive Corp', 'Financials', 'Insurance', 100.0, 1, 1, datetime('now'), datetime('now')),
('sp500-cb', 'CB', 'Chubb Limited', 'Financials', 'Insurance', 100.0, 1, 1, datetime('now'), datetime('now')),
('sp500-spgi', 'SPGI', 'S&P Global Inc.', 'Financials', 'Financial Data', 130.0, 1, 1, datetime('now'), datetime('now')),
('sp500-mco', 'MCO', "Moody's Corporation", 'Financials', 'Financial Data', 85.0, 1, 1, datetime('now'), datetime('now')),
('sp500-ice', 'ICE', 'Intercontinental Exchange', 'Financials', 'Financial Exchanges', 80.0, 1, 1, datetime('now'), datetime('now')),
('sp500-noc', 'NDAQ', 'Nasdaq Inc.', 'Financials', 'Financial Exchanges', 35.0, 1, 1, datetime('now'), datetime('now')),
('sp500-trv', 'TRV', 'The Travelers Companies', 'Financials', 'Insurance', 40.0, 1, 1, datetime('now'), datetime('now')),
('sp500-aig', 'AIG', 'American International Group', 'Financials', 'Insurance', 50.0, 1, 1, datetime('now'), datetime('now')),
('sp500-met', 'MET', 'MetLife Inc.', 'Financials', 'Insurance', 55.0, 1, 1, datetime('now'), datetime('now')),
('sp500-pru', 'PRU', 'Prudential Financial', 'Financials', 'Insurance', 40.0, 1, 1, datetime('now'), datetime('now')),
('sp500-lnc', 'LNC', 'Lincoln National Corp', 'Financials', 'Insurance', 8.0, 1, 1, datetime('now'), datetime('now')),

-- Healthcare
('sp500-unh', 'UNH', 'UnitedHealth Group', 'Healthcare', 'Healthcare Plans', 450.0, 1, 1, datetime('now'), datetime('now')),
('sp500-jnj', 'JNJ', 'Johnson & Johnson', 'Healthcare', 'Drug Manufacturers', 380.0, 1, 1, datetime('now'), datetime('now')),
('sp500-abbv', 'ABBV', 'AbbVie Inc.', 'Healthcare', 'Drug Manufacturers', 300.0, 1, 1, datetime('now'), datetime('now')),
('sp500-lly', 'LLY', 'Eli Lilly and Company', 'Healthcare', 'Drug Manufacturers', 650.0, 1, 1, datetime('now'), datetime('now')),
('sp500-mrk', 'MRK', 'Merck & Co. Inc.', 'Healthcare', 'Drug Manufacturers', 280.0, 1, 1, datetime('now'), datetime('now')),
('sp500-pfe', 'PFE', 'Pfizer Inc.', 'Healthcare', 'Drug Manufacturers', 160.0, 1, 1, datetime('now'), datetime('now')),
('sp500-abt', 'ABT', 'Abbott Laboratories', 'Healthcare', 'Medical Devices', 180.0, 1, 1, datetime('now'), datetime('now')),
('sp500-tmo', 'TMO', 'Thermo Fisher Scientific', 'Healthcare', 'Diagnostics & Research', 200.0, 1, 1, datetime('now'), datetime('now')),
('sp500-dhr', 'DHR', 'Danaher Corporation', 'Healthcare', 'Diagnostics & Research', 180.0, 1, 1, datetime('now'), datetime('now')),
('sp500-bmy', 'BMY', 'Bristol-Myers Squibb', 'Healthcare', 'Drug Manufacturers', 120.0, 1, 1, datetime('now'), datetime('now')),
('sp500-amgn', 'AMGN', 'Amgen Inc.', 'Healthcare', 'Drug Manufacturers', 150.0, 1, 1, datetime('now'), datetime('now')),
('sp500-gild', 'GILD', 'Gilead Sciences Inc.', 'Healthcare', 'Drug Manufacturers', 100.0, 1, 1, datetime('now'), datetime('now')),
('sp500-regs', 'REGN', 'Regeneron Pharmaceuticals', 'Healthcare', 'Drug Manufacturers', 100.0, 1, 1, datetime('now'), datetime('now')),
('sp500-isrg', 'ISRG', 'Intuitive Surgical Inc.', 'Healthcare', 'Medical Devices', 140.0, 1, 1, datetime('now'), datetime('now')),
('sp500-idxx', 'IDXX', 'IDEXX Laboratories', 'Healthcare', 'Diagnostics & Research', 40.0, 1, 1, datetime('now'), datetime('now')),
('sp500-bdx', 'BDX', 'Becton Dickinson', 'Healthcare', 'Medical Instruments', 70.0, 1, 1, datetime('now'), datetime('now')),
('sp500-sykb', 'SYK', 'Stryker Corporation', 'Healthcare', 'Medical Instruments', 120.0, 1, 1, datetime('now'), datetime('now')),
('sp500-bsx', 'BSX', 'Boston Scientific Corp', 'Healthcare', 'Medical Devices', 80.0, 1, 1, datetime('now'), datetime('now')),
('sp500-dxcm', 'DXCM', 'DexCom Inc.', 'Healthcare', 'Medical Devices', 35.0, 1, 1, datetime('now'), datetime('now')),
('sp500-vrtx', 'VRTX', 'Vertex Pharmaceuticals', 'Healthcare', 'Drug Manufacturers', 110.0, 1, 1, datetime('now'), datetime('now')),
('sp500-mrna', 'MRNA', 'Moderna Inc.', 'Healthcare', 'Drug Manufacturers', 35.0, 1, 1, datetime('now'), datetime('now')),
('sp500-biib', 'BIIB', 'Biogen Inc.', 'Healthcare', 'Drug Manufacturers', 30.0, 1, 1, datetime('now'), datetime('now')),
('sp500-hum', 'HUM', 'Humana Inc.', 'Healthcare', 'Healthcare Plans', 55.0, 1, 1, datetime('now'), datetime('now')),
('sp500-cvs', 'CVS', 'CVS Health Corp', 'Healthcare', 'Pharmaceutical Retailers', 80.0, 1, 1, datetime('now'), datetime('now')),
('sp500-elv', 'ELV', 'Elevance Health Inc.', 'Healthcare', 'Healthcare Plans', 100.0, 1, 1, datetime('now'), datetime('now')),
('sp500-ci', 'CI', 'Cigna Corp', 'Healthcare', 'Healthcare Plans', 80.0, 1, 1, datetime('now'), datetime('now')),

-- Consumer Discretionary
('sp500-hd', 'HD', 'The Home Depot Inc.', 'Consumer Discretionary', 'Home Improvement Retail', 350.0, 1, 1, datetime('now'), datetime('now')),
('sp500-mcd', 'MCD', "McDonald's Corporation", 'Consumer Discretionary', 'Restaurants', 200.0, 1, 1, datetime('now'), datetime('now')),
('sp500-nke', 'NKE', 'NIKE Inc.', 'Consumer Discretionary', 'Apparel Manufacturing', 120.0, 1, 1, datetime('now'), datetime('now')),
('sp500-sbux', 'SBUX', 'Starbucks Corporation', 'Consumer Discretionary', 'Restaurants', 100.0, 1, 1, datetime('now'), datetime('now')),
('sp500-low', 'LOW', "Lowe's Companies", 'Consumer Discretionary', 'Home Improvement Retail', 140.0, 1, 1, datetime('now'), datetime('now')),
('sp500-tgt', 'TGT', 'Target Corporation', 'Consumer Discretionary', 'Discount Stores', 70.0, 1, 1, datetime('now'), datetime('now')),
('sp500-tjx', 'TJX', 'TJX Companies Inc.', 'Consumer Discretionary', 'Apparel Retail', 95.0, 1, 1, datetime('now'), datetime('now')),
('sp500-dg', 'DG', 'Dollar General Corp', 'Consumer Discretionary', 'Discount Stores', 25.0, 1, 1, datetime('now'), datetime('now')),
('sp500-dltr', 'DLTR', 'Dollar Tree Inc.', 'Consumer Discretionary', 'Discount Stores', 25.0, 1, 1, datetime('now'), datetime('now')),
('sp500-rost', 'ROST', 'Ross Stores Inc.', 'Consumer Discretionary', 'Apparel Retail', 45.0, 1, 1, datetime('now'), datetime('now')),
('sp500-mar', 'MAR', 'Marriott International', 'Consumer Discretionary', 'Lodging', 70.0, 1, 1, datetime('now'), datetime('now')),
('sp500-hlt', 'HLT', 'Hilton Worldwide Holdings', 'Consumer Discretionary', 'Lodging', 60.0, 1, 1, datetime('now'), datetime('now')),
('sp500- bkng', 'BKNG', 'Booking Holdings Inc.', 'Consumer Discretionary', 'Travel Services', 120.0, 1, 1, datetime('now'), datetime('now')),
('sp500-expe', 'EXPE', 'Expedia Group Inc.', 'Consumer Discretionary', 'Travel Services', 20.0, 1, 1, datetime('now'), datetime('now')),
('sp500-gm', 'GM', 'General Motors Company', 'Consumer Discretionary', 'Auto Manufacturers', 55.0, 1, 1, datetime('now'), datetime('now')),
('sp500-f', 'F', 'Ford Motor Company', 'Consumer Discretionary', 'Auto Manufacturers', 45.0, 1, 1, datetime('now'), datetime('now')),
('sp500-rid', 'RIVN', 'Rivian Automotive', 'Consumer Disditionary', 'Auto Manufacturers', 15.0, 1, 1, datetime('now'), datetime('now')),
('sp500-car', 'CAR', 'Avis Budget Group', 'Consumer Discretionary', 'Rental & Leasing', 10.0, 1, 1, datetime('now'), datetime('now')),
('sp500-has', 'HAS', 'Hasbro Inc.', 'Consumer Discretionary', 'Toys & Games', 8.0, 1, 1, datetime('now'), datetime('now')),
('sp500-mat', 'MAT', 'Mattel Inc.', 'Consumer Discretionary', 'Toys & Games', 6.0, 1, 1, datetime('now'), datetime('now')),
('sp500-lvs', 'LVS', 'Las Vegas Sands', 'Consumer Discretionary', 'Resorts & Casinos', 35.0, 1, 1, datetime('now'), datetime('now')),
('sp500-wynn', 'WYNN', 'Wynn Resorts Ltd', 'Consumer Discretionary', 'Resorts & Casinos', 15.0, 1, 1, datetime('now'), datetime('now')),
('sp500-etsy', 'ETSY', 'Etsy Inc.', 'Consumer Discretionary', 'E-Commerce', 6.0, 1, 1, datetime('now'), datetime('now')),
('sp500-ebay', 'EBAY', 'eBay Inc.', 'Consumer Discretionary', 'E-Commerce', 30.0, 1, 1, datetime('now'), datetime('now')),

-- Consumer Staples
('sp500-pg', 'PG', 'Procter & Gamble Co.', 'Consumer Staples', 'Household Products', 370.0, 1, 1, datetime('now'), datetime('now')),
('sp500-ko', 'KO', 'The Coca-Cola Company', 'Consumer Staples', 'Beverages', 260.0, 1, 1, datetime('now'), datetime('now')),
('sp500-pep', 'PEP', 'PepsiCo Inc.', 'Consumer Staples', 'Beverages', 220.0, 1, 1, datetime('now'), datetime('now')),
('sp500-cost', 'COST', 'Costco Wholesale Corp', 'Consumer Staples', 'Discount Stores', 350.0, 1, 1, datetime('now'), datetime('now')),
('sp500-wmt', 'WMT', 'Walmart Inc.', 'Consumer Staples', 'Discount Stores', 650.0, 1, 1, datetime('now'), datetime('now')),
('sp500-pm', 'PM', 'Philip Morris International', 'Consumer Staples', 'Tobacco', 160.0, 1, 1, datetime('now'), datetime('now')),
('sp500-mo', 'MO', 'Altria Group Inc.', 'Consumer Staples', 'Tobacco', 85.0, 1, 1, datetime('now'), datetime('now')),
('sp500-cl', 'CL', 'Colgate-Palmolive Co.', 'Consumer Staples', 'Household Products', 75.0, 1, 1, datetime('now'), datetime('now')),
('sp500-k', 'K', 'Kellogg Company', 'Consumer Staples', 'Packaged Foods', 25.0, 1, 1, datetime('now'), datetime('now')),
('sp500-gis', 'GIS', 'General Mills Inc.', 'Consumer Staples', 'Packaged Foods', 40.0, 1, 1, datetime('now'), datetime('now')),
('sp500-hrl', 'HRL', 'Hormel Foods Corp', 'Consumer Staples', 'Packaged Foods', 25.0, 1, 1, datetime('now'), datetime('now')),
('sp500-khc', 'KHC', 'Kraft Heinz Company', 'Consumer Staples', 'Packaged Foods', 45.0, 1, 1, datetime('now'), datetime('now')),
('sp500-cag', 'CAG', 'Conagra Brands Inc.', 'Consumer Staples', 'Packaged Foods', 15.0, 1, 1, datetime('now'), datetime('now')),
('sp500-mdlz', 'MDLZ', 'Mondelez International', 'Consumer Staples', 'Packaged Foods', 90.0, 1, 1, datetime('now'), datetime('now')),
('sp500-stz', 'STZ', 'Constellation Brands Inc', 'Consumer Staples', 'Beverages', 45.0, 1, 1, datetime('now'), datetime('now')),
('sp500-bud', 'BUD', 'Anheuser-Busch InBev', 'Consumer Staples', 'Beverages', 100.0, 1, 1, datetime('now'), datetime('now')),
('sp500-syy', 'SYY', 'Sysco Corporation', 'Consumer Staples', 'Food Distribution', 40.0, 1, 1, datetime('now'), datetime('now')),
('sp500-usfd', 'USFD', 'US Foods Holding Corp', 'Consumer Staples', 'Food Distribution', 10.0, 1, 1, datetime('now'), datetime('now')),

-- Industrials
('sp500-cat', 'CAT', 'Caterpillar Inc.', 'Industrials', 'Farm & Heavy Construction Machinery', 180.0, 1, 1, datetime('now'), datetime('now')),
('sp500-de', 'DE', 'Deere & Company', 'Industrials', 'Farm & Heavy Construction Machinery', 130.0, 1, 1, datetime('now'), datetime('now')),
('sp500-ba', 'BA', 'The Boeing Company', 'Industrials', 'Aerospace & Defense', 130.0, 1, 1, datetime('now'), datetime('now')),
('sp500-hon', 'HON', 'Honeywell International', 'Industrials', 'Conglomerates', 130.0, 1, 1, datetime('now'), datetime('now')),
('sp500-ups', 'UPS', 'United Parcel Service', 'Industrials', 'Logistics', 110.0, 1, 1, datetime('now'), datetime('now')),
('sp500-fdx', 'FDX', 'FedEx Corporation', 'Industrials', 'Logistics', 60.0, 1, 1, datetime('now'), datetime('now')),
('sp500-ge', 'GE', 'General Electric Company', 'Industrials', 'Aerospace & Defense', 200.0, 1, 1, datetime('now'), datetime('now')),
('sp500-emr', 'EMR', 'Emerson Electric Co.', 'Industrials', 'Electrical Equipment', 70.0, 1, 1, datetime('now'), datetime('now')),
('sp500-etn', 'ETN', 'Eaton Corporation plc', 'Industrials', 'Electrical Equipment', 120.0, 1, 1, datetime('now'), datetime('now')),
('sp500-lhx', 'LHX', 'L3Harris Technologies', 'Industrials', 'Aerospace & Defense', 40.0, 1, 1, datetime('now'), datetime('now')),
('sp500-noc', 'NOC', 'Northrop Grumman Corp', 'Industrials', 'Aerospace & Defense', 75.0, 1, 1, datetime('now'), datetime('now')),
('sp500-rtn', 'RTX', 'RTX Corporation', 'Industrials', 'Aerospace & Defense', 150.0, 1, 1, datetime('now'), datetime('now')),
('sp500-gd', 'GD', 'General Dynamics Corp', 'Industrials', 'Aerospace & Defense', 70.0, 1, 1, datetime('now'), datetime('now')),
('sp500-lmt', 'LMT', 'Lockheed Martin Corp', 'Industrials', 'Aerospace & Defense', 100.0, 1, 1, datetime('now'), datetime('now')),
('sp500-bld', 'BLD', 'TopBuild Corp', 'Industrials', 'Engineering & Construction', 8.0, 1, 1, datetime('now'), datetime('now')),
('sp500-ppi', 'PPG', 'PPG Industries Inc.', 'Industrials', 'Chemicals', 35.0, 1, 1, datetime('now'), datetime('now')),
('sp500-shw', 'SHW', 'Sherwin-Williams Co', 'Industrials', 'Chemicals', 90.0, 1, 1, datetime('now'), datetime('now')),
('sp500-aph', 'APH', 'Amphenol Corporation', 'Industrials', 'Electronic Components', 80.0, 1, 1, datetime('now'), datetime('now')),
('sp500-tel', 'TEL', 'TE Connectivity Ltd', 'Industrials', 'Electronic Components', 50.0, 1, 1, datetime('now'), datetime('now')),
('sp500-rhi', 'RHI', 'Robert Half International', 'Industrials', 'Staffing & Employment Services', 8.0, 1, 1, datetime('now'), datetime('now')),
('sp500-man', 'MAN', 'ManpowerGroup Inc.', 'Industrials', 'Staffing & Employment Services', 5.0, 1, 1, datetime('now'), datetime('now')),
('sp500-unp', 'UNP', 'Union Pacific Corp', 'Industrials', 'Railroads', 140.0, 1, 1, datetime('now'), datetime('now')),
('sp500-csx', 'CSX', 'CSX Corporation', 'Industrials', 'Railroads', 60.0, 1, 1, datetime('now'), datetime('now')),
('sp500-nsc', 'NSC', 'Norfolk Southern Corp', 'Industrials', 'Railroads', 55.0, 1, 1, datetime('now'), datetime('now')),
('sp500-ksu', 'KSU', 'Kansas City Southern', 'Industrials', 'Railroads', 30.0, 1, 1, datetime('now'), datetime('now')),
('sp500-ws', 'WSM', 'Williams-Sonoma Inc.', 'Consumer Discretionary', 'Home Furnishings', 15.0, 1, 1, datetime('now'), datetime('now')),
('sp500-pnr', 'PNR', 'Pentair plc', 'Industrials', 'Industrial Distribution', 15.0, 1, 1, datetime('now'), datetime('now')),
('sp500-dhr', 'DHR', 'Roper Technologies Inc.', 'Industrials', 'Software', 55.0, 1, 1, datetime('now'), datetime('now')),

-- Energy
('sp500-xom', 'XOM', 'Exxon Mobil Corp', 'Energy', 'Oil & Gas Integrated', 500.0, 1, 1, datetime('now'), datetime('now')),
('sp500-cvx', 'CVX', 'Chevron Corporation', 'Energy', 'Oil & Gas Integrated', 300.0, 1, 1, datetime('now'), datetime('now')),
('sp500-cop', 'COP', 'ConocoPhillips', 'Energy', 'Oil & Gas E&P', 140.0, 1, 1, datetime('now'), datetime('now')),
('sp500-eog', 'EOG', 'EOG Resources Inc.', 'Energy', 'Oil & Gas E&P', 60.0, 1, 1, datetime('now'), datetime('now')),
('sp500-psx', 'PSX', 'Phillips 66', 'Energy', 'Oil & Gas Refining', 55.0, 1, 1, datetime('now'), datetime('now')),
('sp500-vlo', 'VLO', 'Valero Energy Corp', 'Energy', 'Oil & Gas Refining', 45.0, 1, 1, datetime('now'), datetime('now')),
('sp500-mro', 'MRO', 'Marathon Oil Corp', 'Energy', 'Oil & Gas E&P', 25.0, 1, 1, datetime('now'), datetime('now')),
('sp500-mpc', 'MPC', 'Marathon Petroleum', 'Energy', 'Oil & Gas Refining', 55.0, 1, 1, datetime('now'), datetime('now')),
('sp500-oxy', 'OXY', 'Occidental Petroleum', 'Energy', 'Oil & Gas E&P', 50.0, 1, 1, datetime('now'), datetime('now')),
('sp500-apah', 'APA', 'APA Corporation', 'Energy', 'Oil & Gas E&P', 10.0, 1, 1, datetime('now'), datetime('now')),
('sp500-fang', 'FANG', 'Diamondback Energy', 'Energy', 'Oil & Gas E&P', 30.0, 1, 1, datetime('now'), datetime('now')),
('sp500-pioneer', 'PXD', 'Pioneer Natural Resources', 'Energy', 'Oil & Gas E&P', 50.0, 1, 1, datetime('now'), datetime('now')),
('sp500-hes', 'HES', 'Hess Corporation', 'Energy', 'Oil & Gas Integrated', 45.0, 1, 1, datetime('now'), datetime('now')),
('sp500-wmb', 'WMB', 'Williams Companies', 'Energy', 'Oil & Gas Midstream', 50.0, 1, 1, datetime('now'), datetime('now')),
('sp500-et', 'ET', 'Energy Transfer LP', 'Energy', 'Oil & Gas Midstream', 55.0, 1, 1, datetime('now'), datetime('now')),
('sp500-enb', 'ENB', 'Enbridge Inc.', 'Energy', 'Oil & Gas Midstream', 90.0, 1, 1, datetime('now'), datetime('now')),
('sp500-kmi', 'KMI', 'Kinder Morgan Inc.', 'Energy', 'Oil & Gas Midstream', 40.0, 1, 1, datetime('now'), datetime('now')),
('sp500-o ke', 'OKE', 'ONEOK Inc.', 'Energy', 'Oil & Gas Midstream', 40.0, 1, 1, datetime('now'), datetime('now')),
('sp500-slb', 'SLB', 'Schlumberger NV', 'Energy', 'Oil & Gas Equipment & Services', 80.0, 1, 1, datetime('now'), datetime('now')),
('sp500-bkr', 'BKR', 'Baker Hughes Company', 'Energy', 'Oil & Gas Equipment & Services', 35.0, 1, 1, datetime('now'), datetime('now')),
('sp500-hal', 'HAL', 'Halliburton Company', 'Energy', 'Oil & Gas Equipment & Services', 35.0, 1, 1, datetime('now'), datetime('now')),
('sp500-no'v', 'NOV', 'NOV Inc.', 'Energy', 'Oil & Gas Equipment & Services', 6.0, 1, 1, datetime('now'), datetime('now')),
('sp500-bkr', 'F', 'TechnipFMC plc', 'Energy', 'Oil & Gas Equipment & Services', 10.0, 1, 1, datetime('now'), datetime('now')),

-- Utilities
('sp500-nee', 'NEE', 'NextEra Energy Inc.', 'Utilities', 'Utilities - Regulated Electric', 130.0, 1, 1, datetime('now'), datetime('now')),
('sp500-duk', 'DUK', 'Duke Energy Corp', 'Utilities', 'Utilities - Regulated Electric', 80.0, 1, 1, datetime('now'), datetime('now')),
('sp500-so', 'SO', 'The Southern Company', 'Utilities', 'Utilities - Regulated Electric', 85.0, 1, 1, datetime('now'), datetime('now')),
('sp500-d', 'D', 'Dominion Energy Inc.', 'Utilities', 'Utilities - Regulated Electric', 50.0, 1, 1, datetime('now'), datetime('now')),
('sp500-exc', 'EXC', 'Exelon Corporation', 'Utilities', 'Utilities - Regulated Electric', 40.0, 1, 1, datetime('now'), datetime('now')),
('sp500-aep', 'AEP', 'American Electric Power', 'Utilities', 'Utilities - Regulated Electric', 55.0, 1, 1, datetime('now'), datetime('now')),
('sp500-sre', 'SRE', 'Sempra Energy', 'Utilities', 'Utilities - Regulated Electric', 45.0, 1, 1, datetime('now'), datetime('now')),
('sp500-xel', 'XEL', 'Xcel Energy Inc.', 'Utilities', 'Utilities - Regulated Electric', 35.0, 1, 1, datetime('now'), datetime('now')),
('sp500-pnw', 'PNW', 'Pinnacle West Capital', 'Utilities', 'Utilities - Regulated Electric', 10.0, 1, 1, datetime('now'), datetime('now')),
('sp500-es', 'ES', 'Eversource Energy', 'Utilities', 'Utilities - Regulated Electric', 25.0, 1, 1, datetime('now'), datetime('now')),
('sp500-ed', 'ED', 'Consolidated Edison', 'Utilities', 'Utilities - Regulated Electric', 30.0, 1, 1, datetime('now'), datetime('now')),
('sp500-wec', 'WEC', 'WEC Energy Group Inc', 'Utilities', 'Utilities - Regulated Electric', 25.0, 1, 1, datetime('now'), datetime('now')),
('sp500-et 'r', 'ETR', 'Entergy Corporation', 'Utilities', 'Utilities - Regulated Electric', 25.0, 1, 1, datetime('now'), datetime('now')),
('sp500-peg', 'PEG', 'Public Service Enterprise', 'Utilities', 'Utilities - Regulated Electric', 30.0, 1, 1, datetime('now'), datetime('now')),
('sp500-avn', 'AV', 'Avangrid Inc.', 'Utilities', 'Utilities - Regulated Electric', 15.0, 1, 1, datetime('now'), datetime('now')),
('sp500-ni', 'NI', 'NiSource Inc.', 'Utilities', 'Utilities - Regulated Gas', 15.0, 1, 1, datetime('now'), datetime('now')),
('sp500-oui', 'OGE', 'OGE Energy Corp', 'Utilities', 'Utilities - Regulated Electric', 8.0, 1, 1, datetime('now'), datetime('now')),
('sp500-aes', 'AES', 'The AES Corporation', 'Utilities', 'Utilities - Independent Power Producers', 15.0, 1, 1, datetime('now'), datetime('now')),
('sp500-lnt', 'LNT', 'Alliant Energy Corp', 'Utilities', 'Utilities - Regulated Electric', 15.0, 1, 1, datetime('now'), datetime('now')),
('sp500-cms', 'CMS', 'CMS Energy Corp', 'Utilities', 'Utilities - Regulated Electric', 20.0, 1, 1, datetime('now'), datetime('now')),
('sp500-dte', 'DTE', 'DTE Energy Company', 'Utilities', 'Utilities - Regulated Electric', 25.0, 1, 1, datetime('now'), datetime('now')),
('sp500-eix', 'EIX', 'Edison International', 'Utilities', 'Utilities - Regulated Electric', 25.0, 1, 1, datetime('now'), datetime('now')),
('sp500-fe', 'FE', 'FirstEnergy Corp', 'Utilities', 'Utilities - Regulated Electric', 20.0, 1, 1, datetime('now'), datetime('now')),
('sp500-ppl', 'PPL', 'PPL Corporation', 'Utilities', 'Utilities - Regulated Electric', 20.0, 1, 1, datetime('now'), datetime('now')),

-- Real Estate
('sp500-am', 'AMT', 'American Tower Corp', 'Real Estate', 'REIT - Specialty', 100.0, 1, 1, datetime('now'), datetime('now')),
('sp500-pld', 'PLD', 'Prologis Inc.', 'Real Estate', 'REIT - Industrial', 120.0, 1, 1, datetime('now'), datetime('now')),
('sp500-cci', 'CCI', 'Crown Castle Inc.', 'Real Estate', 'REIT - Specialty', 45.0, 1, 1, datetime('now'), datetime('now')),
('sp500-eqv', 'EQIX', 'Equinix Inc.', 'Real Estate', 'REIT - Specialty', 80.0, 1, 1, datetime('now'), datetime('now')),
('sp500-o', 'O', 'Realty Income Corp', 'Real Estate', 'REIT - Retail', 50.0, 1, 1, datetime('now'), datetime('now')),
('sp500-sp'g', 'SPG', 'Simon Property Group', 'Real Estate', 'REIT - Retail', 55.0, 1, 1, datetime('now'), datetime('now')),
('sp500-avb', 'AVB', 'AvalonBay Communities', 'Real Estate', 'REIT - Residential', 30.0, 1, 1, datetime('now'), datetime('now')),
('sp500-ess', 'ESS', 'Essex Property Trust', 'Real Estate', 'REIT - Residential', 20.0, 1, 1, datetime('now'), datetime('now')),
('sp500-uar', 'EQR', 'Equity Residential', 'Real Estate', 'REIT - Residential', 25.0, 1, 1, datetime('now'), datetime('now')),
('sp500-vtr', 'VTR', 'Ventas Inc.', 'Real Estate', 'REIT - Healthcare Facilities', 25.0, 1, 1, datetime('now'), datetime('now')),
('sp500-hcp', 'WELL', 'Welltower Inc.', 'Real Estate', 'REIT - Healthcare Facilities', 70.0, 1, 1, datetime('now'), datetime('now')),
('sp500-dre', 'DRE', 'Duke Realty Corp', 'Real Estate', 'REIT - Industrial', 15.0, 1, 1, datetime('now'), datetime('now')),
('sp500-dl'x', 'DLR', 'Digital Realty Trust', 'Real Estate', 'REIT - Specialty', 45.0, 1, 1, datetime('now'), datetime('now')),
('sp500-psy', 'PSA', 'Public Storage', 'Real Estate', 'REIT - Specialty', 65.0, 1, 1, datetime('now'), datetime('now')),
('sp500-ext', 'EXR', 'Extra Space Storage', 'Real Estate', 'REIT - Specialty', 35.0, 1, 1, datetime('now'), datetime('now')),
('sp500-well', 'WELL', 'Welltower Inc.', 'Real Estate', 'REIT - Healthcare Facilities', 70.0, 1, 1, datetime('now'), datetime('now')),

-- Materials
('sp500-lin', 'LIN', 'Linde plc', 'Materials', 'Chemicals', 220.0, 1, 1, datetime('now'), datetime('now')),
('sp500-apd', 'APD', 'Air Products & Chemicals', 'Materials', 'Chemicals', 65.0, 1, 1, datetime('now'), datetime('now')),
('sp500-ecl', 'ECL', 'Ecolab Inc.', 'Materials', 'Chemicals', 60.0, 1, 1, datetime('now'), datetime('now')),
('sp500-dd', 'DD', 'DuPont de Nemours Inc', 'Materials', 'Chemicals', 35.0, 1, 1, datetime('now'), datetime('now')),
('sp500-ctva', 'CTVA', 'Corteva Inc.', 'Materials', 'Agricultural Inputs', 40.0, 1, 1, datetime('now'), datetime('now')),
('sp500-fmc', 'FMC', 'FMC Corporation', 'Materials', 'Agricultural Inputs', 15.0, 1, 1, datetime('now'), datetime('now')),
('sp500-lyb', 'LYB', 'LyondellBasell Industries', 'Materials', 'Chemicals', 30.0, 1, 1, datetime('now'), datetime('now')),
('sp500-emn', 'EMN', 'Eastman Chemical Co', 'Materials', 'Chemicals', 12.0, 1, 1, datetime('now'), datetime('now')),
('sp500-px', 'PX', 'Praxair Inc.', 'Materials', 'Chemicals', 60.0, 1, 1, datetime('now'), datetime('now')),
('sp500-vmc', 'VMC', 'Vulcan Materials Company', 'Materials', 'Building Materials', 35.0, 1, 1, datetime('now'), datetime('now')),
('sp500-mlm', 'MLM', 'Martin Marietta Materials', 'Materials', 'Building Materials', 30.0, 1, 1, datetime('now'), datetime('now')),
('sp500-nem', 'NEM', 'Newmont Corporation', 'Materials', 'Gold', 55.0, 1, 1, datetime('now'), datetime('now')),
('sp500-fcx', 'FCX', 'Freeport-McMoRan Inc.', 'Materials', 'Copper', 55.0, 1, 1, datetime('now'), datetime('now')),
('sp500-alb', 'ALB', 'Albemarle Corporation', 'Materials', 'Chemicals', 25.0, 1, 1, datetime('now'), datetime('now')),
('sp500-ce', 'CE', 'Celanese Corporation', 'Materials', 'Chemicals', 15.0, 1, 1, datetime('now'), datetime('now')),
('sp500-hun', 'HUN', 'Huntsman Corporation', 'Materials', 'Chemicals', 6.0, 1, 1, datetime('now'), datetime('now')),
('sp500-i ff', 'IFF', 'International Flavors & Fragrances', 'Materials', 'Chemicals', 25.0, 1, 1, datetime('now'), datetime('now')),
('sp500-mos', 'MOS', 'The Mosaic Company', 'Materials', 'Agricultural Inputs', 15.0, 1, 1, datetime('now'), datetime('now')),
('sp500-se', 'SHW', 'Sherwin-Williams Co', 'Materials', 'Chemicals', 90.0, 1, 1, datetime('now'), datetime('now')),

-- Communication Services
('sp500-vz', 'VZ', 'Verizon Communications', 'Communication Services', 'Telecom Services', 170.0, 1, 1, datetime('now'), datetime('now')),
('sp500-t', 'T', 'AT&T Inc.', 'Communication Services', 'Telecom Services', 130.0, 1, 1, datetime('now'), datetime('now')),
('sp500-tmus', 'TMUS', 'T-Mobile US Inc.', 'Communication Services', 'Telecom Services', 250.0, 1, 1, datetime('now'), datetime('now')),
('sp500-dis', 'DIS', 'The Walt Disney Co', 'Communication Services', 'Entertainment', 180.0, 1, 1, datetime('now'), datetime('now')),
('sp500-nflx', 'NFLX', 'Netflix Inc.', 'Communication Services', 'Entertainment', 250.0, 1, 1, datetime('now'), datetime('now')),
('sp500-cmcsa', 'CMCSA', 'Comcast Corporation', 'Communication Services', 'Telecom Services', 160.0, 1, 1, datetime('now'), datetime('now')),
('sp500-charter', 'CHTR', 'Charter Communications', 'Communication Services', 'Telecom Services', 70.0, 1, 1, datetime('now'), datetime('now')),
('sp500-omc', 'OMC', 'Omnicom Group Inc.', 'Communication Services', 'Advertising Agencies', 15.0, 1, 1, datetime('now'), datetime('now')),
('sp500-ipg', 'IPG', 'Interpublic Group', 'Communication Services', 'Advertising Agencies', 10.0, 1, 1, datetime('now'), datetime('now')),
('sp500-spot', 'SPOT', 'Spotify Technology SA', 'Communication Services', 'Entertainment', 60.0, 1, 1, datetime('now'), datetime('now')),
('sp500-paraj', 'PARA', 'Paramount Global', 'Communication Services', 'Entertainment', 15.0, 1, 1, datetime('now'), datetime('now')),
('sp500-wbd', 'WBD', 'Warner Bros. Discovery', 'Communication Services', 'Entertainment', 30.0, 1, 1, datetime('now'), datetime('now')),
('sp500-ea', 'EA', 'Electronic Arts Inc.', 'Communication Services', 'Entertainment', 35.0, 1, 1, datetime('now'), datetime('now')),
('sp500-take', 'TTWO', 'Take-Two Interactive', 'Communication Services', 'Entertainment', 35.0, 1, 1, datetime('now'), datetime('now')),
('sp500-atvi', 'ATVI', 'Activision Blizzard', 'Communication Services', 'Entertainment', 70.0, 1, 1, datetime('now'), datetime('now')),
('sp500-nwsa', 'NWSA', 'News Corporation', 'Communication Services', 'Publishing', 15.0, 1, 1, datetime('now'), datetime('now')),
('sp500-foxa', 'FOXA', 'Fox Corporation', 'Communication Services', 'Broadcasting', 20.0, 1, 1, datetime('now'), datetime('now')),
('sp500-tme', 'TME', 'Tencent Music Entertainment', 'Communication Services', 'Entertainment', 25.0, 1, 1, datetime('now'), datetime('now')),
('sp500-lyv', 'LYV', 'Live Nation Entertainment', 'Communication Services', 'Entertainment', 25.0, 1, 1, datetime('now'), datetime('now'))
;
